name: RDP‑on‑Windows

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    steps:
      - name: Download ngrok
        run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract ngrok to folder
        run: Expand-Archive ngrok.zip -DestinationPath ngrok

      - name: Authenticate ngrok
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable Remote Desktop in registry
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      - name: Enable and start RDP service
        run: |
          Set-Service -Name TermService -StartupType Automatic
          Start-Service -Name TermService

      - name: Open firewall for RDP
        run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Create RDP user
        run: |
          New-LocalUser -Name $Env:RDP_USER -Password (ConvertTo-SecureString $Env:RDP_PASS -AsPlainText -Force) -PasswordNeverExpires
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member $Env:RDP_USER
        env:
          RDP_USER: ${{ secrets.USERNAME }}
          RDP_PASS: ${{ secrets.PASSWORD }}

      - name: Start ngrok tunnel and block job
        run: |
          .\ngrok\ngrok.exe tcp 3389
          Write-Host "RDP is exposed. Press ENTER to exit and shut down."
          Read-Host
